#!/bin/env bash

export OCTAVE_HISTFILE="$XDG_CACHE_HOME/octave_hist"
export OCTAVE_SITE_INITFILE="$XDG_CONFIG_HOME/octave/octaverc"
export DOT_SAGE="$XDG_CONFIG_HOME"/sage
export MAXIMA_USERDIR="$XDG_CONFIG_HOME"/maxima

exec /usr/bin/octave "$@"
