#!/usr/bin/env bash

#export HOME=${XDG_DATA_HOME}/firefox
#
#exec /usr/bin/firefox "$@"
(exec bwrap \
  --symlink usr/lib /lib \
  --symlink usr/lib64 /lib64 \
  --ro-bind /usr/lib /usr/lib \
  --ro-bind /usr/lib64 /usr/lib64 \
  --symlink /usr/lib/firefox/firefox /usr/bin/firefox \
  --ro-bind /usr/share/applications /usr/share/applications \
  --ro-bind /usr/share/ca-certificates /usr/share/ca-certificates \
  --ro-bind /usr/share/fonts /usr/share/fonts \
  --ro-bind /usr/share/glib-2.0 /usr/share/glib-2.0 \
  --ro-bind /usr/share/glvnd /usr/share/glvnd \
  --ro-bind /usr/share/libdrm /usr/share/libdrm \
  --ro-bind /usr/share/mime /usr/share/mime \
  --ro-bind /usr/share/X11/xkb /usr/share/X11/xkb \
  --ro-bind /usr/share/icons /usr/share/icons \
  --ro-bind /usr/share/mime /usr/share/mime \
  --ro-bind /etc/fonts /etc/fonts \
  --ro-bind /etc/machine-id /etc/machine-id \
  --ro-bind /etc/resolv.conf /etc/resolv.conf \
  --dir /run/user/"$(id -u)" \
  --ro-bind /run/user/"$(id -u)"/pulse /run/user/"$(id -u)"/pulse \
  --ro-bind /run/user/"$(id -u)"/wayland-0 /run/user/"$(id -u)"/wayland-0 \
  --dev /dev \
  --dev-bind /dev/dri /dev/dri \
  --ro-bind /sys/dev/char /sys/dev/char \
  --ro-bind /sys/devices/pci0000:00 /sys/devices/pci0000:00 \
  --proc /proc \
  --tmpfs /tmp \
  --bind /home/tonyfettes/.local/share/firefox /home/tonyfettes/.mozilla \
  --ro-bind /home/tonyfettes/.config/qutebrowser /home/tonyfettes/.config/qutebrowser \
  --ro-bind /home/tonyfettes/.config/tridactyl/themes /home/tonyfettes/.config/tridactyl/themes \
  --ro-bind /home/tonyfettes/.icons /home/tonyfettes/.icons \
  --bind /home/tonyfettes/downloads /home/tonyfettes/downloads \
  --unshare-all \
  --share-net \
  --hostname RESTRICTED \
  --setenv HOME /home/tonyfettes \
  --setenv MOZ_ENABLE_WAYLAND 1 \
  --setenv PATH /usr/bin \
  --die-with-parent \
  --new-session \
  /usr/bin/firefox "$@")
